INSERT INTO `USER` (`USERNAME`,`HASHED_PASSWORD`,`FIRSTNAME`,`LASTNAME`,`ROLE`,`CREATE_TIME`,`UPDATE_TIME`)
  VALUES
    ('admin','$2a$12$tb6ww2Gp9Dv1Jixi50H9E.xCZbCwRmFakef8YMobpHRG6DETfS0sy','foo','bar','ADMIN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
    ('user','$2a$12$tb6ww2Gp9Dv1Jixi50H9E.xCZbCwRmFakef8YMobpHRG6DETfS0sy','john','smith','USER',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
    ('operation','$2a$12$tb6ww2Gp9Dv1Jixi50H9E.xCZbCwRmFakef8YMobpHRG6DETfS0sy','opera','t','OPERATION',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());